defaults:
    - default
    - data: kitti_360_DFT
    - _self_

name: "kitti_360_pixelnerf"
model: "bts"
output_path: "outputs/pixelnerf/kitti-360"

num_epochs: 25
batch_size: 16

save_best:
    metric: abs_rel
    sign: -1

data:
    data_fc: 2
    image_size: [192, 640]
    color_aug: true
    is_preprocessed: true
    fisheye_rotation: [0, -15]

model_conf:
    arch: "BTSNet"
    use_code: true
    prediction_mode: default
    sample_color : false

    code:
        num_freqs: 6
        freq_factor: 1.5
        include_input: true

    encoder:
        type: "spatial"
        backbone: "resnet34"
        # freeze: false
        # pretrained: true
        # resnet_layers: 50
        # num_ch_dec: [32,32,64,128,256]
        # d_out: 64

    mlp_coarse:
        type : "resnet"
        n_blocks : 5
        d_hidden : 512

    mlp_fine:
        type : "resnet"
        n_blocks : 3
        d_hidden : 512

    ids_enc_offset_viz: [0]
    
    z_near: 3
    z_far: 80
    inv_z: true

    n_frames_encoder: 1
    n_frames_render: 2
    frame_sample_mode: kitti360-mono

    sample_mode: patch
    patch_size: 8
    ray_batch_size: 512

    flip_augmentation: true

    learn_empty: false
    code_mode: z

loss:
    criterion: "l1+ssim"
    invalid_policy: weight_guided
    lambda_edge_aware_smoothness: 0.001

scheduler:
    type: step
    step_size: 120000
    gamma: 0.1

renderer:
    n_coarse : 64
    n_fine : 32
    n_fine_depth : 16
    depth_std : 1.0
    sched : []
    white_bkgd : false
    lindisp: true
    eval_batch_size: 16384
    hard_alpha_cap: true
