defaults:                       ### This code is to run for slurm config
    - dominik_kitti_360_base
    - _self_

#### Simply comment one of them for usage. (Because we want the same configuration as the model was trained last time.)

## For training
name: "BaseExperimentAttnLayerToken" 

model_conf:
    decoder_heads:
        - type: "MultiViewHead2"
          name: "multiviewhead2"
          freeze: false
          args:
            mlp:
                type: "resnet"
                args:
                    n_blocks: 0
                    d_hidden: 128
            attn_layers: 
                IBRAttn: true
                n_layers: 1
                n_heads: 4
            independent_token:
                type: "FixedViewIndependentToken"
                args: None
            mlp2:
                type: "resnet"
                d_in: 16
                args:
                    n_blocks: 0
                    d_hidden: 16
            dropout_views_rate: 0.5
            dropout_multiviewhead: true
