defaults:                       ### This code is to run for slurm config
    - exp_kitti_360_base
    - _self_

#### Simply comment one of them for usage. (Because we want the same configuration as the model was trained last time.)

## For training
name: "NoDropout"     ## Please name it in case there are various hparam settings to distinguish the diff results easily.

resume_from: "/usr/wiss/muhled/storage/user/outputs/mvbts/kitti-360/NoDropout_backend-None-1_20231025-155613/training_checkpoint_80000.pt"
new_model_architecture: true

model_conf:
    decoder_heads:
        - type: "MultiViewHead"
          name: "multiviewhead"
          freeze: false
          args:
            embedding_encoder:
                type: "pwf"
                d_out: 32
            independent_token:
                type: "FixedViewIndependentToken"
                args: None
            # independent_token:
            #     type: "NeuRayIndependentToken"
            #     args:
            #         n_points_per_ray: 64 # same as renderer.n_coarse
            attn_layers:
                IBRAttn: False
                n_layers: 3
                n_heads: 4
                readout_token:
                    type: "fixed"  # fixed, data, neuray
            probing_layer:

            dropout_views_rate: 0.0
            dropout_multiviewhead: false
